In [4]:
import torch
from torch import nn

net = nn.Sequential(nn.Linear(4, 8), nn.ReLU(), nn.Linear(8, 1))
X = torch.rand(size=(2, 4))
net(X)

print(net[2].state_dict()) 
# .state_dict()获取模型参数状态的方法。‌返回一个字典对象，‌其中包含了模型中所有的参数和对应的值
#>>> OrderedDict([('weight', tensor([[-0.0427, -0.2939, -0.1894,  0.0220, -0.1709, -0.1522, -0.0334, -0.2263]])), ('bias', tensor([0.0887]))])

print(type(net[2].bias))  # <class 'torch.nn.parameter.Parameter'>
print(net[2].bias)
print(net[2].bias.data)

OrderedDict({'weight': tensor([[ 0.3287, -0.1680,  0.0020,  0.0962,  0.3317, -0.1704, -0.1654,  0.1260]]), 'bias': tensor([0.0345])})
<class 'torch.nn.parameter.Parameter'>
Parameter containing:
tensor([0.0345], requires_grad=True)
tensor([0.0345])


In [5]:
print(*[(name, param.shape) for name, param in net[0].named_parameters()])
print(*[(name, param.shape) for name, param in net.named_parameters()])

('weight', torch.Size([8, 4])) ('bias', torch.Size([8]))
('0.weight', torch.Size([8, 4])) ('0.bias', torch.Size([8])) ('2.weight', torch.Size([1, 8])) ('2.bias', torch.Size([1]))


In [8]:
k = [1,4,6,7]
k *= k >=5
k

TypeError: '>=' not supported between instances of 'list' and 'int'

In [9]:
import torch
a = [[[[1,2],[2,3]]]]
a = torch.tensor(a)
print(a)
print(a.shape)

tensor([[[[1, 2],
          [2, 3]]]])
torch.Size([1, 1, 2, 2])


In [2]:
import numpy as np
a=np.array([1,0.2,3,6,1.1,4,4.9])
np.argsort(a)

array([1, 0, 4, 2, 5, 6, 3], dtype=int64)